name: SonarQube Scan

on:
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          projectKey: JAY-Tecmantras_NPPHASE-API-Private
          organization: jay-tecmantras
          token: ${{ secrets.SONAR_TOKEN }}
