name: SonarCloud PR Analysis

on:
  pull_request:
    branches:
      - master      # या अपनी main branch का नाम

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout full history (SonarCloud को पुराने commits compare करने के लिए चाहिए)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Setup .NET SDK (आपके प्रोजेक्ट का टारगेट वर्शन डालें)
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # 3️⃣ Restore + Build (सिर्फ़ build; कोई test/coverage नहीं)
      - run: dotnet restore
      - run: dotnet build --configuration Release

      # 4️⃣ SonarCloud static analysis
      - uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=JAY-Tecmantras_NPPHASE-API-Public
            -Dsonar.organization=jay-tecmantras
            -Dsonar.qualitygate.wait=true
            -Dsonar.sources=NPPHASE.Api,NPPHASE.Data,NPPHASE.Services
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # GitHub से PR decoration के लिए
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}    # SonarCloud token
