name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - run: dotnet restore

      - run: dotnet build --configuration Release

      # Run tests and collect coverage
      - run: dotnet test --configuration Release --collect:"XPlat Code Coverage" --results-directory TestResults

      # Install ReportGenerator to convert coverage to Cobertura
      - run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          export PATH="$PATH:/home/runner/.dotnet/tools"
          reportgenerator \
            "-reports:TestResults/**/coverage.cobertura.xml" \
            "-targetdir:TestResults/CoverageReport" \
            -reporttypes:Xml

      # Verify coverage file exists
      - run: ls -R TestResults

      # SonarCloud analysis
      - uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8
        with:
          args: >
            -Dsonar.projectKey=JAY-Tecmantras_NPPHASE-API-Public
            -Dsonar.organization=jay-tecmantras
            -Dsonar.qualitygate.wait=true
            -Dsonar.cs.opencover.reportsPaths=TestResults/CoverageReport/coverage.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
