name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Setup .NET SDK
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # 3️⃣ SonarCloud cache
      - uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 4️⃣ Restore dependencies
      - run: dotnet restore

      # 5️⃣ Build solution
      - run: dotnet build --configuration Release

      # 6️⃣ Create folder for coverage report
      - name: Create Coverage Folder
        run: mkdir -p TestResults/CoverageReport

      # 7️⃣ Run tests with Coverlet coverage
      - name: Run Tests with Coverage
        run: |
          dotnet tool install --global coverlet.console
          export PATH="$PATH:/home/runner/.dotnet/tools"
          dotnet test --no-build --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=cobertura \
            /p:CoverletOutput=TestResults/CoverageReport/coverage.xml

      # 8️⃣ Verify coverage file exists
      - run: ls -R TestResults

      # 9️⃣ SonarCloud analysis
      - uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8
        with:
          args: >
            -Dsonar.projectKey=JAY-Tecmantras_NPPHASE-API-Public
            -Dsonar.organization=jay-tecmantras
            -Dsonar.qualitygate.wait=true
            -Dsonar.cs.opencover.reportsPaths=TestResults/CoverageReport/coverage.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
