name: SonarCloud

on:
  push:
    branches:
      - master   # अगर आपकी main branch का नाम main है
  pull_request:
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - run: dotnet restore
      - run: dotnet build --configuration Release
      - run: dotnet test --configuration Release --collect:"XPlat Code Coverage" --results-directory TestResults
      - uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8
        with:
          args: >
            -Dsonar.projectKey=JAY-Tecmantras_NPPHASE-API-Public
            -Dsonar.organization=jay-tecmantras
            -Dsonar.qualitygate.wait=true
            -Dsonar.cs.opencover.reportsPaths=**/TestResults/**/coverage.cobertura.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
